import filter from "./icons/filter.svg";
import search from "./icons/search.svg";
import regenerate from "./icons/regenerate.svg";
import open from "./icons/open.svg";
import download from "./icons/download.svg";
import circle_dot from "./icons/circle-dot.svg";
import calendar from "./icons/calendar.svg";
import user from "./icons/user.svg";
import hash from "./icons/hash.svg";
import black_dot from "./icons/black_dot.svg";
import blue_dot from "./icons/blue_dot.svg";
import green_dot from "./icons/green_dot.svg";
import check from "./icons/check.svg";
import double_users from "./icons/double_users.svg";
import services from "./icons/services.svg";
import arrow_down from "./icons/arrow_down.svg";
import select from "./icons/select.svg";
import app_logo from "./icons/app_logo.svg";
import sidebar_icon from "./icons/sidebar.svg";
import arrow_left_right from "./icons/arrow-left-right.svg";
import calendar_days from "./icons/calendar-days.svg";
import ellipse from "./icons/Ellipse 1.svg";
import Frame from "./icons/Frame.svg";
import hourglass from "./icons/hourglass.svg";
import globe from "./icons/globe.svg";
import inbox from "./icons/inbox.svg";
import layout_dashboard from "./icons/layout-dashboard.svg";
import help_circle from "./icons/help-circle.svg";
import link_icon from "./icons/secondary icon.svg";
import cancel_icon from "./icons/cancel_icon.svg";

export { cancel_icon, hourglass, Frame, ellipse, calendar_days, link_icon, arrow_left_right, arrow_down, double_users, services, filter, search, regenerate, open, download, circle_dot, calendar, globe, inbox, layout_dashboard, help_circle, user, hash, black_dot, blue_dot, green_dot, check, select, app_logo, sidebar_icon };